version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "line-template-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pqje9dp3eg4v"
s3_prefix = "line-template-bot"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
